Add support for embedded main menu coloring in VS2019
Wumpf/VSSolutionColor pull request #17
Opened 2019-06-11 15:45 UTC by jasperboot

**This fixes the style issue in #16 or at least the bulk of it.**

This will recolor the main menu by making the background of the menu bar itself transparent and recoloring the text in the same way as the former title bar was done (i.e. using either black or white depending on luminesce).

_This PR will not change the search box, so it will still use the colors as set by the theme._

## Examples

**Example with darker solution color selected:**
![image](https://user-images.githubusercontent.com/1049462/59286631-5ca42d80-8c70-11e9-8025-71bda379a1ee.png)

**Example with brighter solution color selected:**
![image](https://user-images.githubusercontent.com/1049462/59286736-8c533580-8c70-11e9-8aec-a029609ba4a6.png)

2019-06-11 19:39 UTC, Wumpf requested changes
Really nice, thanks! But needs fixing for vs2015
Another small thing, please bump the version number in source.extension.vsixmanifest to 1.6.0

2019-06-11 19:39 UTC, Wumpf commented on SolutionColor/TitleBarColorController.cs
> +                    newController.mainMenuControl = GetDecendantFirstInLine(newController.titleBarContainer, 6);
This throws System.ArgumentOutOfRangeException (from `VisualTreeHelper.GetChild`) when I run it in VS2015, needs to have more safeguards.
Exception is caught and ignored, but means that the plugin is non-functional for vs2015

2019-06-12 10:46 UTC, jasperboot commented
> Another small thing, please bump the version number in source.extension.vsixmanifest to 1.6.0

I've now bumped the version number as requested.

2019-06-12 10:52 UTC, jasperboot commented
I think this should be it for now. In the future I'll open a separate PR to also fix the black/white coloring of the 'system menu' (VS icon on the left of the title bar) and the window control buttons (on the right of the title bar)

![image](https://user-images.githubusercontent.com/1049462/59345636-d3910300-8d10-11e9-8a42-e1741a8dd366.png)

![image](https://user-images.githubusercontent.com/1049462/59345664-e4417900-8d10-11e9-85ad-32ecd902edb9.png)

2019-06-18 08:22 UTC, jasperboot commented
Do you want me to change additional things @Wumpf or is this PR good to go?

2019-06-22 11:08 UTC, Wumpf approved these changes

2019-06-22 11:08 UTC, merged

2019-06-22 11:27 UTC, Wumpf commented
Sorry for the delay. Thanks again for the fix, I've uploaded it to the VS marketplace